// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/Task_6_template/Filter_block.v
// Created: 2024-04-21 06:00:12
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter_block
// Source Path: Task_6_template/DUT/Filter
// Hierarchy Level: 1
// Model version: 1.103
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter_block
          (clk,
           reset,
           In,
           Out);


  input   clk;
  input   reset;
  input   signed [7:0] In;  // int8
  output  signed [24:0] Out;  // sfix25_En16


  wire signed [24:0] filter_out1;  // sfix25_En16


  filter u_filter (.clk(clk),
                   .reset(reset),
                   .filter_in(In),  // int8
                   .filter_out(filter_out1)  // sfix25_En16
                   );

  assign Out = filter_out1;

endmodule  // Filter_block

