// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/Task_6_template/MATLAB_Function.v
// Created: 2024-04-21 07:44:44
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function
// Source Path: Task_6_template/DUT/Algorithm/MATLAB Function
// Hierarchy Level: 2
// Model version: 1.107
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function
          (x0,
           x1,
           x2,
           val,
           detected);


  input   signed [24:0] x0;  // sfix25_En16
  input   signed [24:0] x1;  // sfix25_En16
  input   signed [24:0] x2;  // sfix25_En16
  output  signed [7:0] val;  // int8
  output  detected;


  reg signed [7:0] val_1;  // int8
  reg  detected_1;


  always @(x0, x1, x2) begin
    val_1 = 8'sd0;
    if ((x1 > x2) && (x1 > x0)) begin
      if (((x1[24] == 1'b0) && (x1[23] != 1'b0)) || ((x1[24] == 1'b0) && (x1[23:16] == 8'sb01111111))) begin
        val_1 = 8'sb01111111;
      end
      else if ((x1[24] == 1'b1) && (x1[23] != 1'b1)) begin
        val_1 = 8'sb10000000;
      end
      else begin
        val_1 = x1[23:16] + $signed({1'b0, x1[15] & (( ~ x1[24]) | (|x1[14:0]))});
      end
      detected_1 = 1'b1;
    end
    else begin
      detected_1 = 1'b0;
    end
  end



  assign val = val_1;

  assign detected = detected_1;

endmodule  // MATLAB_Function

